import Script from "next/script";
import type { Metadata } from "next";
import "./styles/globals.css";

export const metadata: Metadata = {
  title: "Le Monde Digital d'Elsa", // Remplacez l'apostrophe par &#39;
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Petit+Formal+Script&family=Raleway:wght@100..900&display=swap');
        </style>
        {/* Google Analytics */}
        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-W41JN60E2V"
        ></Script>
        <Script id="google-analytics">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-W41JN60E2V');
          `}
        </Script>
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}


