version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - my-network
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  nestjs-app:
    build: .
    container_name: nestjs-app
    depends_on:
      - mongodb
    networks:
      - my-network
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/portfolio_backend

networks:
  my-network:
    driver: bridge

volumes:
  mongodb_data:
